version: '3.7'
services:
  backend:  
    container_name: backend
    image: kelompok2/dumbplay
    stdin_open: true
    ports:
     - 5000:5000

  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'dumbplay'
      MYSQL_USER: 'admin123'
      MYSQL_PASSWORD: 'Admin123'
      MYSQL_ROOT_PASSWORD: 'Admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/database:/var/lib/mysql
